/**
 * ONE-TIME production remediation: re-geocode active Locations whose
 * coordinates were generated by MockGeocodingProvider, using the real
 * GoogleGeocodingProvider, BEFORE the production ROUTING_PROVIDER/
 * GEOCODING_PROVIDER env vars are switched to "google".
 *
 * Why this exists: computeRouting() (apps/api/src/modules/loads/routing.ts)
 * now refuses to route mock-geocoded coordinates under a real routing
 * provider (see PR #5) — but that guard only prevents MISUSE, it does not
 * fix the underlying stale coordinates. This script fixes the coordinates
 * directly, narrowly, so posted/active loads' locations are ready before
 * cutover.
 *
 * Scope, deliberately narrow:
 *   - Reads/writes ONLY the `locations` table, and only 4 columns on it:
 *     latitude, longitude, provider_place_id, geocoded_by.
 *   - Never touches `loads` or `pricing_snapshots` — this file imports
 *     nothing from the loads/pricing modules and contains no write against
 *     either table.
 *   - Bypasses createProviderRegistry() entirely: constructs
 *     GoogleGeocodingProvider directly from GOOGLE_GEOCODING_API_KEY (or the
 *     GOOGLE_MAPS_API_KEY fallback), so it works regardless of the current
 *     GEOCODING_PROVIDER/ROUTING_PROVIDER configuration.
 *   - Defaults to a dry run (zero writes, zero Google calls) unless invoked
 *     with --execute.
 *
 * Usage (from apps/api):
 *   pnpm exec tsx scripts/regeocode-mock-locations.ts            # dry run
 *   pnpm exec tsx scripts/regeocode-mock-locations.ts --execute   # writes
 *
 * Never prints the API key, DATABASE_URL, or a full request URL. Logs only
 * location id / city / state — never street address lines, never the raw
 * Google response.
 */
import { createPrismaClient, type Prisma, type PrismaClient } from "@loadtopia/db";
import { GoogleGeocodingProvider, resolveApiKey, type GeocodingProvider } from "@loadtopia/providers";

export interface RemediationLogger {
  info: (fields: Record<string, unknown>, message: string) => void;
  warn: (fields: Record<string, unknown>, message: string) => void;
}

const consoleLogger: RemediationLogger = {
  info: (fields, message) => console.log(JSON.stringify({ level: "info", message, ...fields })),
  warn: (fields, message) => console.warn(JSON.stringify({ level: "warn", message, ...fields })),
};

export interface RemediationOptions {
  /** false (default) = dry run: report only, zero writes, zero Google calls. */
  execute: boolean;
}

export interface RemediationResult {
  dryRun: boolean;
  /** Active locations with geocoded_by = 'mock' found by the query. */
  matched: number;
  /** Locations actually sent to the geocoder (0 in dry-run). */
  attempted: number;
  /** Locations successfully re-geocoded and persisted. */
  updated: number;
  /** Locations that failed geocoding and were left unchanged. */
  failed: number;
  failedLocationIds: string[];
}

type TargetLocation = Prisma.LocationGetPayload<{
  select: {
    id: true;
    addressLine1: true;
    addressLine2: true;
    city: true;
    state: true;
    postalCode: true;
    country: true;
  };
}>;

/**
 * Core remediation logic, independent of the CLI/env wiring below so it can
 * be exercised directly against a real (disposable, non-production) database
 * in tests, with an injected fake GeocodingProvider.
 */
export async function runRemediation(
  prisma: PrismaClient,
  geocoder: GeocodingProvider,
  options: RemediationOptions,
  log: RemediationLogger = consoleLogger,
): Promise<RemediationResult> {
  const candidates: TargetLocation[] = await prisma.location.findMany({
    where: { isActive: true, geocodedBy: "mock" },
    select: {
      id: true,
      addressLine1: true,
      addressLine2: true,
      city: true,
      state: true,
      postalCode: true,
      country: true,
    },
    orderBy: { id: "asc" },
  });

  if (!options.execute) {
    for (const loc of candidates) {
      log.info({ locationId: loc.id, city: loc.city, state: loc.state }, "dry-run: would re-geocode");
    }
    log.info(
      { matched: candidates.length },
      "dry-run complete — no Google call made, no database write performed",
    );
    return {
      dryRun: true,
      matched: candidates.length,
      attempted: 0,
      updated: 0,
      failed: 0,
      failedLocationIds: [],
    };
  }

  let attempted = 0;
  let updated = 0;
  const failedLocationIds: string[] = [];

  for (const loc of candidates) {
    attempted += 1;
    try {
      const result = await geocoder.geocode({
        addressLine1: loc.addressLine1,
        addressLine2: loc.addressLine2 ?? undefined,
        city: loc.city,
        region: loc.state,
        postalCode: loc.postalCode,
        country: loc.country,
      });

      // Explicit column list — name, address fields, isActive, companyId are
      // NEVER part of this write.
      await prisma.location.update({
        where: { id: loc.id },
        data: {
          latitude: result.point.latitude,
          longitude: result.point.longitude,
          providerPlaceId: (result.metadata?.placeId as string | undefined) ?? null,
          geocodedBy: result.provider,
        },
      });

      updated += 1;
      log.info(
        { locationId: loc.id, city: loc.city, state: loc.state, geocodedBy: result.provider },
        "re-geocoded successfully",
      );
    } catch (err) {
      failedLocationIds.push(loc.id);
      log.warn(
        { locationId: loc.id, city: loc.city, state: loc.state, error: (err as Error).message },
        "re-geocode failed; location left unchanged",
      );
    }
  }

  log.info(
    { matched: candidates.length, attempted, updated, failed: failedLocationIds.length, failedLocationIds },
    "remediation run complete",
  );

  return {
    dryRun: false,
    matched: candidates.length,
    attempted,
    updated,
    failed: failedLocationIds.length,
    failedLocationIds,
  };
}

async function main(): Promise<void> {
  const execute = process.argv.includes("--execute");
  const prisma = createPrismaClient();
  try {
    // Resolved (and constructed) regardless of mode: neither call performs any
    // I/O, so this is a harmless fail-fast — a dry run still tells you
    // immediately if the credential isn't configured in this environment.
    const geocoder = new GoogleGeocodingProvider(
      resolveApiKey(process.env.GOOGLE_GEOCODING_API_KEY, process.env.GOOGLE_MAPS_API_KEY),
    );
    consoleLogger.info({ execute }, execute ? "starting remediation (EXECUTE)" : "starting remediation (dry run)");
    const result = await runRemediation(prisma, geocoder, { execute }, consoleLogger);
    if (result.failed > 0) process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
}

// Only run the CLI entrypoint when this file is executed directly (e.g. via
// `tsx scripts/regeocode-mock-locations.ts`) — never when imported by tests.
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    consoleLogger.warn({ error: (err as Error).message }, "remediation run failed to start");
    process.exitCode = 1;
  });
}
